import category1 from '../assets/product1Png.png';
import category3 from '../assets/product2Png.png';
import category2 from '../assets/product3Png.png';
import category4 from '../assets/product4Png.png';

export const categories = [
    {
        name: 'category1',
        image: category1,
        color: '#EAECF1'
    },
    {
        name: 'category2',
        image: category2,
        color: '#CEE3F7'
    },
    {
        name: 'category3',
        image: category3,
        color: '#FFD4D1'
    },
    {
        name: 'category4',
        image: category4,
        color: '#F4FFBB'
    }
];
export const products = {
    category1: [
        {
            id: 1,
            name: 'Product 1',
            price: '120KM',
            oldPrice: '250KM',
            rating: '1.8',
            image: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image2: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image3: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image4: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            previewImg: 'https://i.ibb.co/HGdKG1k/product1.png',
            color: '#F4FFBB'
        },
        {
            id: 2,
            name: 'Product 2',
            price: '220KM',
            oldPrice: '300KM',
            rating: '5.0',
            image: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image2: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image3: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image4: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            previewImg: 'https://i.ibb.co/ZSdqpgg/product2.png',
            color: '#EAECF1'
        },
        {
            id: 3,
            name: 'Product 3',
            price: '100KM',
            oldPrice: '210KM',
            rating: '4.1',
            image: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image2: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image3: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image4: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            previewImg: 'https://i.ibb.co/71JNcyf/product3.png',
            color: '#FFD4D1'
        },
        {
            id: 4,
            name: 'Product 4',
            price: '320KM',
            oldPrice: '450KM',
            rating: '3.6',
            image: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image2: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image3: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image4: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            previewImg: 'https://i.ibb.co/K72tpzz/product4.png',
            color: '#CEE3F7'
        },
        {
            id: 5,
            name: 'Product 5',
            price: '220KM',
            oldPrice: '300KM',
            rating: '4.9',
            image: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image2: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image3: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image4: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            previewImg: 'https://i.ibb.co/ZSdqpgg/product2.png',
            color: '#F4FFBB'
        },
        {
            id: 6,
            name: 'Product 6',
            price: '320KM',
            oldPrice: '450KM',
            rating: '3.6',
            image: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image2: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image3: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image4: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            previewImg: 'https://i.ibb.co/K72tpzz/product4.png',
            color: '#CEE3F7'
        },
        {
            id: 7,
            name: 'Product 7',
            price: '120KM',
            oldPrice: '250KM',
            rating: '5.0',
            image: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image2: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image3: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image4: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            previewImg: 'https://i.ibb.co/HGdKG1k/product1.png',
            color: '#EAECF1'
        },
        {
            id: 8,
            name: 'Product 8',
            price: '100KM',
            oldPrice: '210KM',
            rating: '4.9',
            image: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image2: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image3: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image4: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            previewImg: 'https://i.ibb.co/71JNcyf/product3.png',
            color: '#F4FFBB'
        },
    ],
    category2: [
        {
            id: 9,
            name: 'Product 1',
            price: '220KM',
            oldPrice: '300KM',
            rating: '4.2',
            image: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image2: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image3: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image4: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            previewImg: 'https://i.ibb.co/ZSdqpgg/product2.png',
            color: '#EAECF1'
        },
        {
            id: 10,
            name: 'Product 2',
            price: '320KM',
            oldPrice: '450KM',
            rating: '3.6',
            image: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image2: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image3: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image4: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            previewImg: 'https://i.ibb.co/K72tpzz/product4.png',
            color: '#FFD4D1'
        },
        {
            id: 11,
            name: 'Product 3',
            price: '120KM',
            oldPrice: '250KM',
            rating: '1.8',
            image: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image2: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image3: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image4: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            previewImg: 'https://i.ibb.co/HGdKG1k/product1.png',
            color: '#F4FFBB'
        },
        {
            id: 12,
            name: 'Product 4',
            price: '100KM',
            oldPrice: '210KM',
            rating: '4.9',
            image: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image2: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image3: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image4: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            previewImg: 'https://i.ibb.co/71JNcyf/product3.png',
            color: '#CEE3F7'
        },
        {
            id: 13,
            name: 'Product 5',
            price: '120KM',
            oldPrice: '250KM',
            rating: '4.9',
            image: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image2: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image3: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image4: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            previewImg: 'https://i.ibb.co/HGdKG1k/product1.png',
            color: '#FFD4D1'
        },
        {
            id: 14,
            name: 'Product 6',
            price: '220KM',
            oldPrice: '300KM',
            rating: '4.2',
            image: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image2: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image3: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image4: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            previewImg: 'https://i.ibb.co/ZSdqpgg/product2.png',
            color: '#CEE3F7'
        },
        {
            id: 15,
            name: 'Product 7',
            price: '100KM',
            oldPrice: '210KM',
            rating: '4.9',
            image: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image2: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image3: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image4: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            previewImg: 'https://i.ibb.co/71JNcyf/product3.png',
            color: '#F4FFBB'
        },
        {
            id: 16,
            name: 'Product 8',
            price: '320KM',
            oldPrice: '450KM',
            rating: '3.6',
            image: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image2: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image3: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image4: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            previewImg: 'https://i.ibb.co/K72tpzz/product4.png',
            color: '#EAECF1'
        },
    ],
    category3: [
        {
            id: 17,
            name: 'Product 2',
            price: '220KM',
            oldPrice: '300KM',
            rating: '4.9',
            image: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image2: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image3: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image4: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            previewImg: 'https://i.ibb.co/ZSdqpgg/product2.png',
            color: '#FFD4D1'
        },
        {
            id: 18,
            name: 'Product 2',
            price: '320KM',
            oldPrice: '450KM',
            rating: '3.6',
            image: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image2: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image3: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image4: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            previewImg: 'https://i.ibb.co/K72tpzz/product4.png',
            color: '#CEE3F7'
        },
        {
            id: 19,
            name: 'Product 3',
            price: '120KM',
            oldPrice: '250KM',
            rating: '1.8',
            image: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image2: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image3: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image4: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            previewImg: 'https://i.ibb.co/HGdKG1k/product1.png',
            color: '#F4FFBB'
        },
        {
            id: 20,
            name: 'Product 4',
            price: '220KM',
            oldPrice: '300KM',
            rating: '4.2',
            image: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image2: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image3: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image4: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            previewImg: 'https://i.ibb.co/ZSdqpgg/product2.png',
            color: '#CEE3F7'
        },
        {
            id: 21,
            name: 'Product 5',
            price: '100KM',
            oldPrice: '210KM',
            rating: '4.9',
            image: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image2: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image3: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image4: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            previewImg: 'https://i.ibb.co/71JNcyf/product3.png',
            color: '#EAECF1'
        },
        {
            id: 22,
            name: 'Product 6',
            price: '320KM',
            oldPrice: '450KM',
            rating: '5.0',
            image: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image2: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image3: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image4: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            previewImg: 'https://i.ibb.co/K72tpzz/product4.png',
            color: '#FFD4D1'
        },
        {
            id: 23,
            name: 'Product 7',
            price: '100KM',
            oldPrice: '210KM',
            rating: '4.9',
            image: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image2: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image3: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image4: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            previewImg: 'https://i.ibb.co/71JNcyf/product3.png',
            color: '#EAECF1'
        },
        {
            id: 24,
            name: 'Product 8',
            price: '120KM',
            oldPrice: '250KM',
            rating: '1.8',
            image: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image2: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image3: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image4: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            previewImg: 'https://i.ibb.co/HGdKG1k/product1.png',
            color: '#CEE3F7'
        },
    ],
    category4: [
        {
            id: 25,
            name: 'Product 1',
            price: '320KM',
            oldPrice: '450KM',
            rating: '3.6',
            image: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image2: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image3: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image4: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            previewImg: 'https://i.ibb.co/K72tpzz/product4.png',
            color: '#EAECF1'
        },
        {
            id: 26,
            name: 'Product 2',
            price: '220KM',
            oldPrice: '300KM',
            rating: '4.2',
            image: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image2: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image3: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image4: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            previewImg: 'https://i.ibb.co/ZSdqpgg/product2.png',
            color: '#CEE3F7'
        },
        {
            id: 27,
            name: 'Product 3',
            price: '120KM',
            oldPrice: '250KM',
            rating: '1.8',
            image: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image2: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image3: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image4: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            previewImg: 'https://i.ibb.co/HGdKG1k/product1.png',
            color: '#FFD4D1'
        },
        {
            id: 28,
            name: 'Product 4',
            price: '100KM',
            oldPrice: '210KM',
            rating: '4.9',
            image: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image2: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image3: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image4: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            previewImg: 'https://i.ibb.co/71JNcyf/product3.png',
            color: '#CEE3F7'
        },
        {
            id: 29,
            name: 'Product 5',
            price: '120KM',
            oldPrice: '250KM',
            rating: '1.8',
            image: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image2: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image3: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            image4: 'https://i.ibb.co/5kv5fv4/product1-Png.png',
            previewImg: 'https://i.ibb.co/HGdKG1k/product1.png',
            color: '#FFD4D1'
        },
        {
            id: 30,
            name: 'Product 6',
            price: '220KM',
            oldPrice: '300KM',
            rating: '4.2',
            image: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image2: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image3: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            image4: 'https://i.ibb.co/jV7zyg8/product2-Png.png',
            previewImg: 'https://i.ibb.co/ZSdqpgg/product2.png',
            color: '#CEE3F7'
        },
        {
            id: 31,
            name: 'Product 7',
            price: '100KM',
            oldPrice: '210KM',
            rating: '4.9',
            image: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image2: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image3: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            image4: 'https://i.ibb.co/ZJswLmG/product3-Png.png',
            previewImg: 'https://i.ibb.co/71JNcyf/product3.png',
            color: '#F4FFBB'
        },
        {
            id: 32,
            name: 'Product 8',
            price: '320KM',
            oldPrice: '450KM',
            rating: '3.6',
            image: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image2: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image3: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            image4: 'https://i.ibb.co/gWhRpn1/product4-Png.png',
            previewImg: 'https://i.ibb.co/K72tpzz/product4.png',
            color: '#EAECF1'
        },
    ]
}
